name: platelets
channels:
- conda-forge
dependencies:
- pip=24.0
- python=3.10.13
- pip:
  - aiobotocore==2.12.1
  - aiohttp==3.9.3
  - aioitertools==0.11.0
  - aiosignal==1.3.1
  - alabaster==0.7.16
  - annotated-types==0.6.0
  - annotrack==0.0.3
  - app-model==0.2.5
  - appdirs==1.4.4
  - appnope==0.1.4
  - asciitree==0.3.3
  - asttokens==2.4.1
  - async-timeout==4.0.3
  - attrs==23.2.0
  - Babel==2.14.0
  - botocore==1.34.51
  - build==1.1.1
  - cachey==0.2.1
  - certifi==2024.2.2
  - charset-normalizer==3.3.2
  - click==8.1.7
  - cloudpickle==3.0.0
  - comm==0.2.2
  - contourpy==1.2.0
  - cramjam==2.8.2
  - cycler==0.12.1
  - dask==2024.3.1
  - debugpy==1.8.1
  - decorator==5.1.1
  - distributed==2024.3.1
  - docstring_parser==0.16
  - docutils==0.20.1
  - exceptiongroup==1.2.0
  - executing==2.0.1
  - fasteners==0.19
  - fastparquet==2024.2.0
  - filelock==3.13.1
  - fonttools==4.50.0
  - freetype-py==2.4.0
  - frozenlist==1.4.1
  - fsspec==2024.3.1
  - HeapDict==1.0.1
  - hsluv==5.0.4
  - idna==3.6
  - imageio==2.34.0
  - imagesize==1.4.1
  - importlib_metadata==7.0.2
  - in-n-out==0.2.0
  - ipykernel==6.29.3
  - ipython==8.22.2
  - iterseg==0.3.0
  - jedi==0.19.1
  - Jinja2==3.1.3
  - jmespath==1.0.1
  - joblib==1.3.2
  - jsonschema==4.21.1
  - jsonschema-specifications==2023.12.1
  - jupyter_client==8.6.1
  - jupyter_core==5.7.2
  - kiwisolver==1.4.5
  - lazy_loader==0.3
  - llvmlite==0.42.0
  - locket==1.0.0
  - looseversion==1.3.0
  - magicgui==0.8.2
  - markdown-it-py==3.0.0
  - MarkupSafe==2.1.5
  - matplotlib==3.8.3
  - matplotlib-inline==0.1.6
  - mdurl==0.1.2
  - mpmath==1.3.0
  - msgpack==1.0.8
  - multidict==6.0.5
  - napari==0.4.19.post1
  - napari-console==0.0.9
  - napari-plugin-engine==0.2.0
  - napari-svg==0.1.10
  - nest-asyncio==1.6.0
  - networkx==3.2.1
  - npe2==0.7.4
  - numba==0.59.0
  - numcodecs==0.12.1
  - numpy==1.26.4
  - numpydoc==1.6.0
  - ome-zarr==0.8.3
  - packaging==24.0
  - pandas==2.2.1
  - parso==0.8.3
  - partd==1.4.1
  - pexpect==4.9.0
  - pillow==10.2.0
  - Pint==0.23
  - plateletanalysis==0.0.4
  - platetrack==0.0.7
  - platformdirs==4.2.0
  - pooch==1.8.1
  - prompt-toolkit==3.0.43
  - psutil==5.9.8
  - psygnal==0.10.2
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pyarrow==15.0.2
  - pyconify==0.1.6
  - pydantic==2.6.4
  - pydantic-compat==0.1.2
  - pydantic_core==2.16.3
  - Pygments==2.17.2
  - pynndescent==0.5.11
  - PyOpenGL==3.1.7
  - pyparsing==3.1.2
  - pyproject_hooks==1.0.0
  - PyQt5==5.15.10
  - PyQt5-Qt5==5.15.13
  - PyQt5-sip==12.13.0
  - python-dateutil==2.9.0.post0
  - pytz==2024.1
  - PyYAML==6.0.1
  - pyzmq==25.1.2
  - qtconsole==5.5.1
  - QtPy==2.4.1
  - referencing==0.34.0
  - requests==2.31.0
  - rich==13.7.1
  - rpds-py==0.18.0
  - s3fs==2024.3.1
  - scikit-image==0.22.0
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
  - seaborn==0.13.2
  - six==1.16.0
  - snowballstemmer==2.2.0
  - sortedcontainers==2.4.0
  - Sphinx==7.2.6
  - sphinxcontrib-applehelp==1.0.8
  - sphinxcontrib-devhelp==1.0.6
  - sphinxcontrib-htmlhelp==2.0.5
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==1.0.7
  - sphinxcontrib-serializinghtml==1.1.10
  - stack-data==0.6.3
  - superqt==0.6.2
  - sympy==1.12
  - tabulate==0.9.0
  - tblib==3.0.0
  - threadpoolctl==3.3.0
  - tifffile==2024.2.12
  - tomli==2.0.1
  - tomli_w==1.0.0
  - toolz==0.12.1
  - torch==2.2.1
  - tornado==6.4
  - tqdm==4.66.2
  - trackpy==0.6.2
  - traitlets==5.14.2
  - typer==0.9.0
  - typing_extensions==4.10.0
  - tzdata==2024.1
  - umap-learn==0.5.5
  - umetrix==0.2.0
  - urllib3==2.0.7
  - vispy==0.14.2
  - wcwidth==0.2.13
  - wrapt==1.16.0
  - yarl==1.9.4
  - zarr==2.17.1
  - zict==3.0.0
  - zipp==3.18.1
